/**
 * Parser for Claude Code session logs (JSONL format)
 * Reads logs generated by .claude/hooks/session-logger.sh
 */

// ── Types ──

export type LogEventType =
  | 'session_start'
  | 'session_end'
  | 'session_summary'
  | 'tool_start'
  | 'tool_end'
  | 'subagent_start'
  | 'subagent_end'
  | 'unknown';

export interface LogEvent {
  timestamp: string;
  session_id: string;
  event: LogEventType;
  data: Record<string, unknown>;
}

export interface ToolStartData {
  tool: string;
  input: Record<string, unknown>;
}

export interface ToolEndData {
  tool: string;
  output: Record<string, unknown>;
}

export interface SubagentStartData {
  type: string;
  prompt: string;
}

export interface SubagentEndData {
  type: string;
}

export interface SessionSummaryData {
  tool_calls: number;
  subagent_calls: number;
}

// Parsed and enriched log entry
export interface ParsedLogEntry {
  id: string;
  timestamp: Date;
  sessionId: string;
  eventType: LogEventType;

  // For tool events
  toolName?: string;
  toolInput?: Record<string, unknown>;
  toolOutput?: Record<string, unknown>;

  // For subagent events
  subagentType?: string;
  subagentPrompt?: string;

  // For session events
  projectDir?: string;
  reason?: string;

  // For summary
  totalToolCalls?: number;
  totalSubagentCalls?: number;

  // Duration (calculated for tool_end and subagent_end)
  durationMs?: number;

  // Raw data for debugging
  raw: LogEvent;
}

export interface SessionLog {
  sessionId: string;
  startTime?: Date;
  endTime?: Date;
  entries: ParsedLogEntry[];
  toolCalls: { name: string; count: number }[];
  subagentCalls: { type: string; count: number }[];
  totalToolCalls: number;
  totalSubagentCalls: number;
  projectDir?: string;
}

// ── Parsing ──

/**
 * Parse a single JSONL line into a LogEvent
 */
export function parseLogLine(line: string): LogEvent | null {
  const trimmed = line.trim();
  if (!trimmed) return null;

  try {
    return JSON.parse(trimmed) as LogEvent;
  } catch (e) {
    console.warn('Failed to parse log line:', line, e);
    return null;
  }
}

/**
 * Parse JSONL content (multiple lines) into LogEvents
 */
export function parseLogContent(content: string): LogEvent[] {
  return content
    .split('\n')
    .map(parseLogLine)
    .filter((e): e is LogEvent => e !== null);
}

/**
 * Enrich a LogEvent into a ParsedLogEntry with extracted fields
 */
export function enrichLogEntry(event: LogEvent, index: number): ParsedLogEntry {
  const entry: ParsedLogEntry = {
    id: `${event.session_id}-${index}`,
    timestamp: new Date(event.timestamp),
    sessionId: event.session_id,
    eventType: event.event,
    raw: event,
  };

  switch (event.event) {
    case 'tool_start': {
      const data = event.data as unknown as ToolStartData;
      entry.toolName = data.tool;
      entry.toolInput = data.input;
      break;
    }
    case 'tool_end': {
      const data = event.data as unknown as ToolEndData;
      entry.toolName = data.tool;
      entry.toolOutput = data.output;
      break;
    }
    case 'subagent_start': {
      const data = event.data as unknown as SubagentStartData;
      entry.subagentType = data.type;
      entry.subagentPrompt = data.prompt;
      break;
    }
    case 'subagent_end': {
      const data = event.data as unknown as SubagentEndData;
      entry.subagentType = data.type;
      break;
    }
    case 'session_start': {
      entry.projectDir = event.data.project_dir as string;
      break;
    }
    case 'session_end': {
      entry.reason = event.data.reason as string;
      break;
    }
    case 'session_summary': {
      const data = event.data as unknown as SessionSummaryData;
      entry.totalToolCalls = data.tool_calls;
      entry.totalSubagentCalls = data.subagent_calls;
      break;
    }
  }

  return entry;
}

/**
 * Calculate durations by matching start/end events
 */
export function calculateDurations(entries: ParsedLogEntry[]): ParsedLogEntry[] {
  const toolStarts = new Map<string, ParsedLogEntry>();
  const subagentStarts = new Map<string, ParsedLogEntry>();

  return entries.map(entry => {
    if (entry.eventType === 'tool_start' && entry.toolName) {
      toolStarts.set(entry.toolName, entry);
    } else if (entry.eventType === 'tool_end' && entry.toolName) {
      const start = toolStarts.get(entry.toolName);
      if (start) {
        entry.durationMs = entry.timestamp.getTime() - start.timestamp.getTime();
        toolStarts.delete(entry.toolName);
      }
    } else if (entry.eventType === 'subagent_start' && entry.subagentType) {
      subagentStarts.set(entry.subagentType, entry);
    } else if (entry.eventType === 'subagent_end' && entry.subagentType) {
      const start = subagentStarts.get(entry.subagentType);
      if (start) {
        entry.durationMs = entry.timestamp.getTime() - start.timestamp.getTime();
        subagentStarts.delete(entry.subagentType);
      }
    }
    return entry;
  });
}

/**
 * Aggregate entries into a SessionLog
 */
export function aggregateSession(entries: ParsedLogEntry[]): SessionLog {
  const sessionId = entries[0]?.sessionId || 'unknown';

  const toolCounts = new Map<string, number>();
  const subagentCounts = new Map<string, number>();

  let startTime: Date | undefined;
  let endTime: Date | undefined;
  let projectDir: string | undefined;

  for (const entry of entries) {
    if (entry.eventType === 'session_start') {
      startTime = entry.timestamp;
      projectDir = entry.projectDir;
    } else if (entry.eventType === 'session_end') {
      endTime = entry.timestamp;
    } else if (entry.eventType === 'tool_start' && entry.toolName) {
      toolCounts.set(entry.toolName, (toolCounts.get(entry.toolName) || 0) + 1);
    } else if (entry.eventType === 'subagent_start' && entry.subagentType) {
      subagentCounts.set(entry.subagentType, (subagentCounts.get(entry.subagentType) || 0) + 1);
    }
  }

  const toolCalls = Array.from(toolCounts.entries())
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count);

  const subagentCalls = Array.from(subagentCounts.entries())
    .map(([type, count]) => ({ type, count }))
    .sort((a, b) => b.count - a.count);

  return {
    sessionId,
    startTime,
    endTime,
    entries,
    toolCalls,
    subagentCalls,
    totalToolCalls: toolCalls.reduce((sum, t) => sum + t.count, 0),
    totalSubagentCalls: subagentCalls.reduce((sum, s) => sum + s.count, 0),
    projectDir,
  };
}

/**
 * Full parse pipeline: content -> enriched session log
 */
export function parseSessionLog(content: string): SessionLog {
  const events = parseLogContent(content);
  const entries = events.map((e, i) => enrichLogEntry(e, i));
  const withDurations = calculateDurations(entries);
  return aggregateSession(withDurations);
}

// ── Display Helpers ──

export function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
  return `${(ms / 60000).toFixed(1)}m`;
}

export function formatTimestamp(date: Date): string {
  return date.toLocaleTimeString('en-US', {
    hour12: false,
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  });
}

export function getEventIcon(eventType: LogEventType): string {
  switch (eventType) {
    case 'session_start': return '🚀';
    case 'session_end': return '🏁';
    case 'session_summary': return '📊';
    case 'tool_start': return '🔧';
    case 'tool_end': return '✅';
    case 'subagent_start': return '🤖';
    case 'subagent_end': return '✨';
    default: return '❓';
  }
}

export function getEventColor(eventType: LogEventType): string {
  switch (eventType) {
    case 'session_start': return '#22c55e'; // green
    case 'session_end': return '#ef4444'; // red
    case 'session_summary': return '#8b5cf6'; // purple
    case 'tool_start': return '#3b82f6'; // blue
    case 'tool_end': return '#06b6d4'; // cyan
    case 'subagent_start': return '#f59e0b'; // amber
    case 'subagent_end': return '#eab308'; // yellow
    default: return '#6b7280'; // gray
  }
}
